baseURL = "https://ashley.github.io/mentorship/"
languageCode = "en-us"
title = "Guide to College Tech Mentorship"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
footer = "@msashleychen"
footerlink = "https://www.twitter.com/msashleychen"

