baseURL = "https://tips-for-mentorship.firebaseapp.com/"
languageCode = "en-us"
title = "Guide to College Tech Mentorship"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
footer = "@msashleychen"
footerlink = "https://www.twitter.com/msashleychen"

